structure(list(url = "https://api.github.com/none/existent/endpoint", 
    status_code = 404L, headers = structure(list(server = "GitHub.com", 
        date = "Fri, 09 Dec 2022 13:16:09 GMT", `content-type` = "application/json; charset=utf-8", 
        `x-github-media-type` = "github.v3", `x-github-api-version-selected` = "2022-11-28", 
        `access-control-expose-headers` = "ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset", 
        `access-control-allow-origin` = "*", `strict-transport-security` = "max-age=31536000; includeSubdomains; preload", 
        `x-frame-options` = "deny", `x-content-type-options` = "nosniff", 
        `x-xss-protection` = "0", `referrer-policy` = "origin-when-cross-origin, strict-origin-when-cross-origin", 
        `content-security-policy` = "default-src 'none'", vary = "Accept-Encoding, Accept, X-Requested-With", 
        `content-encoding` = "gzip", `x-ratelimit-limit` = "60", 
        `x-ratelimit-remaining` = "56", `x-ratelimit-reset` = "1670592787", 
        `x-ratelimit-resource` = "core", `x-ratelimit-used` = "4", 
        `content-length` = "91", `x-github-request-id` = "69BF:8942:D12A500:D3FC401:63933519"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 404L, version = "HTTP/2", 
        headers = structure(list(server = "GitHub.com", date = "Fri, 09 Dec 2022 13:16:09 GMT", 
            `content-type` = "application/json; charset=utf-8", 
            `x-github-media-type` = "github.v3", `x-github-api-version-selected` = "2022-11-28", 
            `access-control-expose-headers` = "ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset", 
            `access-control-allow-origin` = "*", `strict-transport-security` = "max-age=31536000; includeSubdomains; preload", 
            `x-frame-options` = "deny", `x-content-type-options` = "nosniff", 
            `x-xss-protection` = "0", `referrer-policy` = "origin-when-cross-origin, strict-origin-when-cross-origin", 
            `content-security-policy` = "default-src 'none'", 
            vary = "Accept-Encoding, Accept, X-Requested-With", 
            `content-encoding` = "gzip", `x-ratelimit-limit` = "60", 
            `x-ratelimit-remaining` = "56", `x-ratelimit-reset` = "1670592787", 
            `x-ratelimit-resource` = "core", `x-ratelimit-used` = "4", 
            `content-length` = "91", `x-github-request-id` = "69BF:8942:D12A500:D3FC401:63933519"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = logical(0), 
        flag = logical(0), path = logical(0), secure = logical(0), 
        expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), row.names = integer(0), class = "data.frame"), 
    content = charToRaw("{\"message\":\"Not Found\",\"documentation_url\":\"https://docs.github.com/rest\"}"), 
    date = structure(1670591769, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 2.6e-05, 
    connect = 2.7e-05, pretransfer = 0.000127, starttransfer = 0.190192, 
    total = 0.1903)), class = "response")
