language: r
cache: packages

r:
  - oldrel
  - release
  - devel

r_github_packages:
  - jimhester/covr
  - jimhester/lintr
  - r-lib/pkgdown

after_success:
  - R CMD INSTALL $PKG_TARBALL
  - |
    if [[ "$TRAVIS_R_VERSION_STRING" == "release" ]] && [[ "$TRAVIS_EVENT_TYPE" == "push" ]]; then
      Rscript -e 'lintr::lint_package()'
      Rscript -e 'covr::codecov()'
    fi
  - rm -rf imongr.Rcheck

deploy:
  # our site to gh_pages
  - provider: script
    script: Rscript -e 'pkgdown::deploy_site_github()'
    skip_cleanup: true
    keep_history: false
    on:
      branch: master
      condition: $TRAVIS_R_VERSION_STRING == "release"
