on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: test-coverage

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test-coverage:
    runs-on: ubuntu-24.04
    env:
      GITHUB_PAT: ${{ secrets.GH_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
  
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::covr, any::xml2
          needs: coverage

      - uses: r-lib/actions/setup-pandoc@v2

      - name: Test coverage
        run: covr::codecov(token = "${{ secrets.CODECOV_TOKEN }}")
        shell: Rscript {0}
